---
  alaxy_info:
  author: Doncho2926
  description: Install Docker and Docker Compose on Ubuntu.
  company: ""
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal

dependencies: []
