name: Ansible Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ansible and ansible-lint
        run: |
          pip install ansible ansible-lint

      - name: Run ansible-lint on roles
        run: |
          ansible-lint roles/install_docker
          ansible-lint roles/run_nginx_website